spring.application.name=Social-Media-Platform
# 1. Supabase Database Configuration (Using Transaction Pooler)
spring.datasource.url=jdbc:postgresql://your dadabase link
spring.datasource.username=your username
spring.datasource.password=your password
# Hibernate Properties for PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# 2. Gmail Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Security Configuration
jwt.secret=your_random_jwt_secret_key
jwt.expiration=86400000
# Caching
spring.cache.type=simple
